// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLChA-SRq-SnN5XHkdUyMiiagPhfkWPKo',
    appId: '1:937287956245:web:ce418a1e2a7b786ef0db1c',
    messagingSenderId: '937287956245',
    projectId: 'd-najo-homes',
    authDomain: 'd-najo-homes.firebaseapp.com',
    storageBucket: 'd-najo-homes.appspot.com',
    measurementId: 'G-9D3XGX9W7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8pXWm9HhHlekjxYT47Bc_ftDwqOiyZDs',
    appId: '1:937287956245:android:1a50b50ac01111f0f0db1c',
    messagingSenderId: '937287956245',
    projectId: 'd-najo-homes',
    storageBucket: 'd-najo-homes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWULxfFpPQqANQcgWtPACzR6-tnRUDE44',
    appId: '1:937287956245:ios:d5f00d4edcc64779f0db1c',
    messagingSenderId: '937287956245',
    projectId: 'd-najo-homes',
    storageBucket: 'd-najo-homes.appspot.com',
    iosClientId: '937287956245-nq90edqdq1rlideemj8mgvur58ab93th.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstate',
  );
}
